spring:
  datasource:
    url: jdbc:postgresql://128.199.199.32:5432/microservices_db
    username: ${postgres_username}
    password: ${postgres_password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect